config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:destroy] do
    resources :outreach_reports, only: [:new, :create]
  end

  scope module: 'internal' do
    resources :teams, only: [:new, :create, :edit, :update, :delete] do
      resources :memberships, only: [:create, :destroy]
    end
    get '/dashboard' => 'dashboard#index', as: 'internal_root'
  end

  scope :rankings do
    get '/' => 'rankings#index', as: 'rankings'
    get '/users' => 'rankings#user', as: 'user_rankings'
    get '/teams' => 'rankings#teams', as: 'team_rankings'
  end
  resources :teams, only: [:index, :show]
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'register' => 'users#new', as: 'register'
  delete 'logout' => 'sessions#destroy', as: 'logout'
  root 'site#landing'
end

app/views/shared/_flash.html.haml
- flashes = {:notice => 'success', :alert => 'standard', :error => 'alert', :secondary => 'secondary'}
- flashes.each do |key, value|
  - if flash[key]
    .alert-box.callout.text-center{:class => value, :data => { :closable => ''} }
      = flash[key]
      %button.close-button{type: 'button', data: {'close': ''}} &times;

app/views/shared/_header.html.haml
.top-bar
  .top-bar-title
    %span{data: {"responsive-toggle": "responsive-menu", "hide-for": "medium"}}
      %span.menu-icon.dark{data: {"toggle": ""}}
    %strong
      = link_to "Phonebank Duel", root_path
  #responsive-menu
    .top-bar-right
      - if current_user
        #modal

      %ul.menu.dropdown{data: {"dropdown-menu": ""}}
        %li.menu-text
          = link_to 'Rankings', rankings_path
        - if current_user
          %li.menu-text
            = link_to 'File Report', '#', id: 'fileReport', data: {userId: current_user.id}
          %li.menu-text
            = link_to current_user, '#'
            %ul.menu.vertical
              %li
                = link_to 'Profile', internal_root_path
              %li
                = link_to 'Logout', logout_path, method: :delete
        - else
          %li.menu-text
            = link_to 'Register', register_path
          %li.menu-text
            = link_to 'Login', login_path